services:
    mongo-db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo-db

    database-api:
        image: python:3.12-slim 
        ports:
            - 8000:8000
        expose:
            - 8000
        volumes:
            - ./:/app
        restart: always
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONDONTWRITEBYTECODE=1
        command: >
            bash -c "
                cd app && 
                pip install --no-cache-dir -r requirements.txt && 
                uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
            "
        depends_on:
            - mongo-db

volumes:
    mongodb_data:
