services:
    mongo-db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
        networks:
            - suppl-ai-shared-network

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo-db
        networks:
            - suppl-ai-shared-network

    database-api:
        container_name: database-api
        image: python:3.12-slim
        ports:
            - 8000:8000
        expose:
            - 8000
        volumes:
            - ./:/app
        restart: always
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONDONTWRITEBYTECODE=1
            - MONGO_DB_URL=mongo-db:27017
            - LLM_API_URL=http://llm-api:8001
        command: >
            bash -c "
                cd app && 
                pip install --no-cache-dir -r requirements.txt && 
                uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
            "
        depends_on:
            - mongo-db
        networks:
            - suppl-ai-shared-network

volumes:
    mongodb_data:


networks:
    suppl-ai-shared-network:
        external: true
